// Generated by CoffeeScript 1.6.3
module.exports = function(robot) {
  var Speaker, dir, fs, lame, path, _;
  path = require('path');
  fs = require('fs');
  lame = require('lame');
  Speaker = require('speaker');
  _ = require('underscore');
  dir = path.resolve(__dirname, 'sounds');
  robot.respond(/play (.*)$/i, function(msg) {
    var pipe, stream;
    stream = fs.createReadStream(path.resolve(dir, "" + msg.match[1] + ".mp3"));
    pipe = stream.pipe(new lame.Decoder());
    pipe.on('format', function(format) {
      return this.pipe(new Speaker(format));
    });
    return msg.send("Playing sound " + msg.match[1]);
  });
  return robot.respond(/sounds/i, function(msg) {
    msg.send("The following sounds are available:");
    return _.each(fs.readdirSync(dir), function(file) {
      return msg.send(file);
    });
  });
};
